// Variant data configuration
// Note: distanceToDNA and closestDNAAtom will be populated dynamically by DistanceCalculator
export const variants = [
    { name: 'p.Met1Ile', residue: 1, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Leu12Phe', residue: 12, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Val61Gly', residue: 61, type: 'Likely Benign', color: '#f5d547', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly68Arg', residue: 68, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly76Cys', residue: 76, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Glu78Ter', residue: 78, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Glu78Asp', residue: 78, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asp82Asn', residue: 82, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Leu92Phe', residue: 92, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Glu101Ter', residue: 101, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Glu105Lys', residue: 105, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Val110Gly', residue: 110, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg112Pro', residue: 112, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ile125Thr', residue: 125, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Lys126Arg', residue: 126, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.His132Pro', residue: 132, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asn133Ser', residue: 133, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.His135Asn', residue: 135, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln136Glu', residue: 136, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln136Ter', residue: 136, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Glu138Lys', residue: 138, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Leu145Gln', residue: 145, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asn146Asp', residue: 146, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln147Ter', residue: 147, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln147Glu', residue: 147, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser148Leu', residue: 148, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser148Trp', residue: 148, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Phe148Leu', residue: 148, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser151Pro', residue: 151, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser151Cys', residue: 151, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.His153Asn', residue: 153, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Lys156Glu', residue: 156, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Thr158Asn', residue: 158, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Pro159Leu', residue: 159, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Met160Val', residue: 160, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Lys164Gln', residue: 164, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg165His', residue: 165, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg165Pro', residue: 165, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ala167Thr', residue: 167, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Leu168Pro', residue: 168, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Tyr169His', residue: 169, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Trp171Ter', residue: 171, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Trp171*', residue: 171, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Trp171Cys', residue: 171, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Val173Ile', residue: 173, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln176Ter', residue: 176, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln176*', residue: 176, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg177*', residue: 177, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg177Gln', residue: 177, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg181Ter', residue: 181, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg181*', residue: 181, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg181Gln', residue: 181, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln182Ter', residue: 182, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln182*', residue: 182, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser197Arg', residue: 197, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asn228Lys', residue: 228, type: 'Likely Benign', color: '#f5d547', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg232Cys', residue: 232, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg233His', residue: 233, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg235Gln', residue: 235, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg235Glu', residue: 235, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg235Trp', residue: 235, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Trp238Leu', residue: 238, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly239Glu', residue: 239, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln248*', residue: 248, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asp251Asn', residue: 251, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln253Pro', residue: 253, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Pro256Ser', residue: 256, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg261Gly', residue: 261, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Cys273Tyr', residue: 273, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Cys273Ser', residue: 273, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln275*', residue: 275, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg276Gly', residue: 276, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg276*', residue: 276, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg276Gln', residue: 276, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg276Ter', residue: 276, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly285Asp', residue: 285, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg295His', residue: 295, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg295Cys', residue: 295, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg295Pro', residue: 295, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Trp299Gly', residue: 299, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asn302Lys', residue: 302, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg303His', residue: 303, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Lys305*', residue: 305, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln311Ter', residue: 311, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.His336Asp', residue: 336, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.His336Arg', residue: 336, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser342Pro', residue: 342, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Pro343Leu', residue: 343, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly370Ser', residue: 370, type: 'Likely Benign', color: '#f5d547', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser379Ter', residue: 379, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln382*', residue: 382, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asn418Thr', residue: 418, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln454Ter', residue: 454, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser465Arg', residue: 465, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln470Ter', residue: 470, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg527Gln', residue: 527, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Met532Val', residue: 532, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser547Phe', residue: 547, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null }
];

// UNPARSED VARIANTS FROM CSV
// These variants could not be automatically converted to protein notation (p. format)
// They are preserved here for reference and potential manual conversion
// Total unparsed: 134
/*
const unparsedVariants = [
  // cDNA notation variants (c.)
  'c.1006C>G',
  'c.1006C>G',
  'c.1006C>G',
  'c.1006C>G',
  'c.1045+12T>C (heterozygous)',
  'c.1099A>G, p.(Ser367Gly)',
  'c.1206 +1G>C IVS5',
  'c.1206+ 1G>A',
  'c.1240-2A>G',
  'c.130G>T, (Glu44Ter)',
  'c.130G>T, p.(Glu44*)',
  'c.130G>T, p.(Glu44Ter)',
  'c.1340-1G>A',
  'c.1340-1G>A',
  'c.1340-1G>A',
  'c.1340-1G>A',
  'c.1395C>G, p.(S465R)',
  'c.1492C>T; p.GIn498* ',
  'c.1654–2A>T, IVS8_2A>T',
  'c.182T>G, p.(Val61Gly)',
  'c.226G>T, p.(Gly76Cys)',
  'c.226G>T, p.(Gly76Cys)',
  'c.232G>T',
  'c.232G>T',
  'c.313G>A',
  'c.344+2 T>C',
  'c.344+2T>C',
  'c.344+2T>C',
  'c.345-1G>T',
  'c.391C>T',
  'c.395A>G, p.(His132Arg)',
  'c.406C>T, p.(Gln136*)',
  'c.443C>T, p.(Ser148Leu)',
  'c.443C>T, p.(Ser148Leu)',
  'c.444C>T, S148L',
  'c.455A>G, (Gln152Arg)',
  'c.493C > T',
  'c.493C>G; p.(Arg165Gly)',
  'c.493C>G; p.(Arg165Gly)',
  'c.493C>T, p.(Arg165Cys)',
  'c.494G>A, p.(R165H)',
  'c.508A>C, p.(Thr170Pro)',
  'c.517G > C',
  'c.523A>T, p.(Lys175Ter)',
  'c.529C>T, p.(rg177Ter)',
  'c.543+1G>T, IVS2+1G>T',
  'c.543C>T, R181X',
  'c.544+1G>A',
  'c.544+1G>A (heterozygous)',
  'c.544+1G>T',
  'c.544+1G>T',
  'c.544+1G>T ',
  'c.554C>T, Gln182*',
  'c.578t>C, p.(Leu264Ser)',
  'c.715G>C, p.(Gly239Arg)',
  'c.742C>T, p.(Gln248Ter)',
  'c.826C>T',
  'c.826C>T, p.(Arg276Ter)',
  'c.827G>A',
  'c.827G>A',
  'c.854G>A, p.(Gly285Asp)',
  'c.854G>A, p.(Gly285Asp)',
  'c.854G>A, p.(Gly285Asp)',
  'c.857T>G, p.(Leu286Arg)',
  'c.865A>C, p.(Asn289His)',
  'c.865A>C, p.(Asn289His)',
  'c.865A>C, p.(Asn289His)',
  'c.883C>T',
  'c.883C>T, p.(Arg295Cys)',
  'c.883C>T, p.(Arg295Cys)',
  'c.883C>T, p.(Arg295Cys)',
  'c.884G>A, p.(Arg295His)',
  'c.884G>A, p.(Arg295His)',
  'c.884G>A, p.(Arg295His)',
  'c.908G>A, p.(Arg303His)',
  'c.940G>A, p.(Ala314Thr)',
  // Intronic variants (IVS)
  'IVS1 345-1G->A',
  'IVS1 345-1G->A',
  'IVS2+1G->T',
  'IVS2+1G>C',
  'IVS2+1G>T',
  'IVS2nt + 1G>A',
  'IVS2nt + 1G>A',
  'IVS2nt + 1G>A',
  'IVS2nt+1G>A',
  'IVS2nt+1G>A',
  'IVS2nt+1G>A',
  'IVS2nt+1G>T',
  'IVS2nt+1G>T',
  'IVS2nt+1G>T',
  'IVS2nt+1G>T',
  'IVS2nt+1G>T',
  'IVS2nt+1G>T',
  'IVS2nt+1G>T',
  'IVS2􏰁1G􏰂T',
  'IVS2􏰁1G􏰂T',
  'IVS2􏰁1G􏰂T',
  'IVS2􏰁1G􏰂T',
  'IVS2􏰁1G􏰂T',
  'IVS2􏰁1G􏰂T',
  'IVS2􏰁1G􏰂T',
  'IVS3 809 + 1G>A',
  'IVS3nt-4C>G',
  'IVS6 + 1G>A',
  'c.1206 +1G>C IVS5',
  'c.1654–2A>T, IVS8_2A>T',
  'c.543+1G>T, IVS2+1G>T',
  // Other variants
  'Gln136X',
  'Gln136X',
  'Gln311*',
  'Gly76Cys',
  'Gly76Cys',
  'R181ter',
  'R181ter',
  'R182ter',
  'R182ter',
  'exon 7 GGC > AGC 135, p.(Gly492Ser)',
  'exon 7 GGC > AGC 135, p.(Gly492Ser)',
  'exon 7 GGC > AGC 135, p.(Gly492Ser)',
  'exon 7 GGC > AGC 135, p.(Gly492Ser)',
  'exon a GCG > ACG 177, p.(Ala241Thr)',
  'p.(Arg177*)',
  'p.(Arg177*)',
  'p.(Arg177*)',
  'p.(Arg177*)',
  'p.(Arg177*)',
  'p.(Arg177*)',
  'p.(Arg177*)',
  'p.(Glu260Asp)',
  'p.(Glu260Asp)',
  'p.(Glu260Asp)',
  'p.(Glu260Asp)',
  'p.(Glu260Asp)',
  'p.(Glu260Asp)',
  'p.(Ser36Phe)',
  'p.(Ser36Phe)',
  '−67C>T',
];
*/
