// Variant data configuration
// Note: distanceToDNA and closestDNAAtom will be populated dynamically by DistanceCalculator
export const variants = [
    { name: 'p.Met1Ile', residue: 1, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Leu12Phe', residue: 12, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser36Phe', residue: 36, type: 'Likely Benign', color: '#f5d547', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Val61Gly', residue: 61, type: 'Likely Benign', color: '#f5d547', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly68Arg', residue: 68, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly76Cys', residue: 76, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Glu78Asp', residue: 78, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asp82Asn', residue: 82, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Leu92Phe', residue: 92, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Glu105Lys', residue: 105, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Val110Gly', residue: 110, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg112Pro', residue: 112, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ile125Thr', residue: 125, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Lys126Arg', residue: 126, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.His132Pro', residue: 132, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.His132Arg', residue: 132, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asn133Ser', residue: 133, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln136Glu', residue: 136, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Glu138Lys', residue: 138, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Leu145Gln', residue: 145, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln147Glu', residue: 147, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser148Leu', residue: 148, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser148Trp', residue: 148, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser151Pro', residue: 151, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser151Cys', residue: 151, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln152Arg', residue: 152, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.His153Asn', residue: 153, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asn155Asp', residue: 155, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Lys156Glu', residue: 156, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Thr158Asn', residue: 158, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Pro159Leu', residue: 159, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Met160Val', residue: 160, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Lys164Gln', residue: 164, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg165His', residue: 165, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg165Pro', residue: 165, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg165Cys', residue: 165, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg165Gly', residue: 165, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ala167Thr', residue: 167, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Leu168Pro', residue: 168, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Tyr169His', residue: 169, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Thr170Pro', residue: 170, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Trp171Cys', residue: 171, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Val173Ile', residue: 173, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Val173Leu', residue: 173, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg177Gln', residue: 177, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg181Gln', residue: 181, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser197Arg', residue: 197, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asn228Lys', residue: 228, type: 'Likely Benign', color: '#f5d547', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg232Cys', residue: 232, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg233His', residue: 233, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg235Gln', residue: 235, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg235Trp', residue: 235, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Trp238Leu', residue: 238, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly239Arg', residue: 239, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly239Glu', residue: 239, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ala241Thr', residue: 241, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asp251Asn', residue: 251, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gln253Pro', residue: 253, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Pro256Ser', residue: 256, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Glu260Asp', residue: 260, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg261Gly', residue: 261, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Leu264Ser', residue: 264, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Cys273Tyr', residue: 273, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Cys273Ser', residue: 273, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg276Gly', residue: 276, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg276Gln', residue: 276, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly285Asp', residue: 285, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Leu286Arg', residue: 286, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asn289His', residue: 289, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg295Cys', residue: 295, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg295His', residue: 295, type: 'Pathogenic', color: 'red', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg295Pro', residue: 295, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Trp299Gly', residue: 299, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asn302Lys', residue: 302, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg303His', residue: 303, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ala314Thr', residue: 314, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.His336Asp', residue: 336, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.His336Arg', residue: 336, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser342Pro', residue: 342, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Pro343Leu', residue: 343, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser367Gly', residue: 367, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly370Ser', residue: 370, type: 'Likely Benign', color: '#f5d547', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Asn418Thr', residue: 418, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser465Arg', residue: 465, type: 'Likely Pathogenic', color: 'orange', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Gly492Ser', residue: 492, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Arg527Gln', residue: 527, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Met532Val', residue: 532, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null },
    { name: 'p.Ser547Phe', residue: 547, type: 'Uncertain Significance', color: 'grey', distanceToDNA: null, closestDNAAtom: null }
];

// UNPARSED VARIANTS FROM CSV
// These variants could not be automatically converted to protein notation (p. format)
// They are preserved here for reference and potential manual conversion
// Total unparsed: 70
/*
const unparsedVariants = [
  // Other variants
  'HNF1B(NM_000458.4):c.-67C>T',
  'HNF1B(NM_000458.4):c.1045+12T>C',
  'HNF1B(NM_000458.4):c.1046-2A>G',
  'HNF1B(NM_000458.4):c.1206+1G>A',
  'HNF1B(NM_000458.4):c.1206+1G>C',
  'HNF1B(NM_000458.4):c.1339+1G>A',
  'HNF1B(NM_000458.4):c.1340-1G>A',
  'HNF1B(NM_000458.4):c.1340-1G>A',
  'HNF1B(NM_000458.4):c.1340-1G>A',
  'HNF1B(NM_000458.4):c.1340-1G>A',
  'HNF1B(NM_000458.4):c.1654-2A>T',
  'HNF1B(NM_000458.4):c.344+2T>C',
  'HNF1B(NM_000458.4):c.344+2T>C',
  'HNF1B(NM_000458.4):c.344+2T>C',
  'HNF1B(NM_000458.4):c.345-1G>A',
  'HNF1B(NM_000458.4):c.345-1G>A',
  'HNF1B(NM_000458.4):c.345-1G>T',
  'HNF1B(NM_000458.4):c.544+1G>A',
  'HNF1B(NM_000458.4):c.544+1G>A',
  'HNF1B(NM_000458.4):c.544+1G>A',
  'HNF1B(NM_000458.4):c.544+1G>A',
  'HNF1B(NM_000458.4):c.544+1G>A',
  'HNF1B(NM_000458.4):c.544+1G>A',
  'HNF1B(NM_000458.4):c.544+1G>A',
  'HNF1B(NM_000458.4):c.544+1G>A',
  'HNF1B(NM_000458.4):c.544+1G>C',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.544+1G>T',
  'HNF1B(NM_000458.4):c.809+1G>A',
  'HNF1B(NM_000458.4):c.810-4C>G',
  'p.Arg177Ter (termination variant)',
  'p.Arg181Ter (termination variant)',
  'p.Arg276Ter (termination variant)',
  'p.Gln131Ter (termination variant)',
  'p.Gln136Ter (termination variant)',
  'p.Gln147Ter (termination variant)',
  'p.Gln176Ter (termination variant)',
  'p.Gln182Ter (termination variant)',
  'p.Gln248Ter (termination variant)',
  'p.Gln275Ter (termination variant)',
  'p.Gln311Ter (termination variant)',
  'p.Gln382Ter (termination variant)',
  'p.Gln454Ter (termination variant)',
  'p.Gln470Ter (termination variant)',
  'p.Gln498Ter (termination variant)',
  'p.Glu101Ter (termination variant)',
  'p.Glu44Ter (termination variant)',
  'p.Glu78Ter (termination variant)',
  'p.Lys175Ter (termination variant)',
  'p.Lys305Ter (termination variant)',
  'p.Ser379Ter (termination variant)',
  'p.Trp171Ter (termination variant)',
];
*/
